sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - pypy
    - pypy3
install:
    - pip install mock coverage coveralls
    - pip install .
script:
    - coverage run --source=src/restview setup.py test -q
after_success:
    - coveralls
notifications:
    email: false
